### ISSUE TITLE
The resize-observer-polyfill plugin is able to add support for listening to css3 "animation" to change element size?

### ISSUE THREAD

**Issue by wuwhs** [que-etc/resize-observer-polyfill#60]
Hi,
First of all, thanks for the excellent plugin,I have applied it to my project.In your code,you use "transitionend" to listen for "CSS transition", which causes the size of the element to change, but "animation" may also cause element changes. 

```js
  // Subscription to the "Transitionend" event is used as a workaround for
  // delayed transitions. This way it's possible to capture at least the
  // final state of an element.
  document.addEventListener('transitionend', this.onTransitionEnd_);
  window.addEventListener('resize', this.refresh);
```
For example the following example

There is a element which use css3 animation in my container,
```css
  #tar {
      width: 200px;
      height: 200px;
      background-color: aqua;
      border: 1px solid #ccc;
      animation: changeheight 2s ease-in 1s infinite;
    }

    @keyframes changeheight {
      0% {
        height: 300px;
      }
      50% {
        height: 200px;
      }
      100% {
        height: 300px;
      }
    }
```
when the inner element height change,then need to update the height of the outer 'iscroll' container, and call the `refresh()` method.resize-observer-polyfill plugin can't cover this situation.
Wish you reply yet,thanks!
